### ISSUE TITLE
Actual state of this library

### ISSUE THREAD

**Issue by adelura** [philipwalton/mozart#2]
Hey,

I've read your [article](http://philipwalton.com/articles/implementing-private-and-protected-members-in-javascript/) about private properties in JS and it leads me here.

According to [readme](https://github.com/philipwalton/mozart#feedback-and-contributing):

> It's not a finished product, it's a work in progress.

Time passed, article is quite old and your last contribution was done more than one year ago.

Do you have any new thoughts about solution which you proposed with mozart library?

**Comment by philipwalton** [comment]
The first part of that paragraph is the most important part, in terms of how I think of the library:

> While Mozart is a working library it's also a proof-of-concept for how inheritance and privacy could be done better in JavaScript.

The library still works and does everything it's supposed to. It hasn't been updated recently because no one has filed any bugs for it. It's API hasn't changed either because JavaScript, the language, hasn't really changed enough to support new privacy features.

Once ES2015 proxies become implemented in all modern browsers, I think that will be the preferred way to do privacy going forward.

**Comment by mightyiam** [comment]
@philipwalton do you have any current recommendation that addresses the same issues?

**Comment by philipwalton** [comment]
@mightyiam no, not at this point. I haven't spent much more time thinking about it.
