### ISSUE TITLE
Calling a public method from a protected method

### ISSUE THREAD

**Issue by koyote130708** [philipwalton/mozart#4]
It seems it's not possible to access public properties from a protected method because there is no way to get the instance of the public prototype.

For example:

``` js
var Foo = ctor("Foo", function (prototype, _, _protected) {
    Object.assign(prototype, {
        init: function (name) {
            this._name = name;
        },
        saySecret: function () {
            console.log(_(this).secret());
        },
        getName: function () {
            return this._name;
        },
        printName: function () {
            _(this).sayName();
        }
    });

    Object.assign(_protected, {
        secret: function () {
            return "This is a secret";
        },
        sayName: function () {
            console.log(this.getName()); // this doesn't work
            console.log(prototype.getName.call(this)); // this doesn't work either
        }
    });
});

var foo = new Foo("Foo");

foo.saySecret(); 
foo.printName(); // this fails
```

Although we can access the protected properties from anywhere using "_(this)", we can only access the public properties within the public context (inside the methods declared for the public prototype).

It would be nice to have a function like "_()" that gives back the instance of the public prototype by passing in the instance of the protected or private prototype.

**Comment by philipwalton** [comment]
Yeah, this is a trade-off. The way it's currently designed, the protected key object sets the parent class's protected prototype as it's prototype, which is what allows for inheritance.
https://github.com/philipwalton/mozart/blob/master/test/class.js#L128-L141

If JavaScript allowed for multiple inheritance, then you'd be able to set both objects in the prototype chain and get what you're after.

I think this is just a limitation of the library, public methods can call private/protected methods, but not the other way around if you _also_ want to have inheritance. Note that in the private parts module, this works just fine since the public instance is set as the prototype when the private instance is created.
https://github.com/philipwalton/private-parts/blob/master/test/create-key.js#L53-L62
